RedHatInsights/policies-ui-backend

- README.adoc
- pom.xml
- src/main/java/com/redhat/cloud/custompolicies/app/rest/FactService.java
- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
> Bump Quarkus to 1.0.0.Final and supply OpenApi

- src/main/java/com/redhat/cloud/custompolicies/app/rest/FactService.java
- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
- src/main/resources/META-INF/openapi.json
- src/test/java/com/redhat/cloud/custompolicies/app/RestApiTest.java
> Adjust base path to conventions.

- .travis.yml
Add initial travis test config and pr to test travis config.
>  Add initial travis test config.

- README.adoc
- src/main/resources/META-INF/openapi.json
- src/main/resources/application.properties
> Update README and OpenApi base definitions.

- src/main/java/com/redhat/cloud/custompolicies/app/JaxRsApplication.java
- src/main/java/com/redhat/cloud/custompolicies/app/rest/FactService.java
- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
> Use a JaxRs application class to provide the base path.

- .gitignore
- README.adoc
- deploy/Dockerfile
- deploy/create_docker_image.sh
- src/main/java/com/redhat/cloud/custompolicies/app/VerifyEngine.java
- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
- src/main/resources/application.properties
Allow to build container images.
This is off of master and may/will clash with #6 so one or the other will need rebasing
> Allow building container-images.

- pom.xml
- src/main/java/com/redhat/cloud/custompolicies/app/model/Policy.java
- src/main/java/com/redhat/cloud/custompolicies/app/model/pager/Page.java
- src/main/java/com/redhat/cloud/custompolicies/app/model/pager/Pager.java
- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
- src/main/java/com/redhat/cloud/custompolicies/app/rest/utils/PagingUtils.java
- src/test/java/com/redhat/cloud/custompolicies/app/rest/utils/PagingUtilsTest.java
~~I'm adding `lombok`, it needs IDE configuration to function properly:~~
~~Eclipse: https://projectlombok.org/setup/eclipse
Intelli: https://projectlombok.org/setup/intellij~~
Removed it
> CPOL-42 Allows pagination

- src/main/java/com/redhat/cloud/custompolicies/app/EngineResponseExceptionMapper.java
- src/main/java/com/redhat/cloud/custompolicies/app/VerifyEngine.java
- src/main/java/com/redhat/cloud/custompolicies/app/model/FullTrigger.java
- src/main/java/com/redhat/cloud/custompolicies/app/model/Policy.java
- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
- src/test/java/com/redhat/cloud/custompolicies/app/RestApiTest.java
Change the way we talk to the engine, as this now expects a different URL and data structure.
> Talk to new engine

- pom.xml
- src/main/java/com/redhat/cloud/custompolicies/app/health/ReadinessProbe.java
This is a first version, that for sure needs more work.
I would like to deploy this to CI in order to play with it there.
> Deploy a health check with readiness probe.

- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
- src/test/java/com/redhat/cloud/custompolicies/app/RestApiTest.java
This was missing a path segment, as the api of UriBuilder is a bit cryptic
> Fix generation of Location header and test this.

- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
> Add types for parameters and header

- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
> [CPOL-41] Return a better message when the engine is not reachable.

- src/main/java/com/redhat/cloud/custompolicies/app/model/Policy.java
- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
- src/main/java/com/redhat/cloud/custompolicies/app/rest/utils/PagingUtils.java
- src/main/resources/db/migration/V3.sql
- src/test/java/com/redhat/cloud/custompolicies/app/TestPolicy.java
Explicitly sort by name if no sort column is given.
Add 'last updated' column with the name 'mtime'.
> Add mtime column and make sort default to 'mtime'

- README.adoc
- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
- src/test/resources/example-policy.json
> Improve documentation.

- src/main/java/com/redhat/cloud/custompolicies/app/EngineResponseExceptionMapper.java
- src/main/java/com/redhat/cloud/custompolicies/app/VerifyEngine.java
- src/main/java/com/redhat/cloud/custompolicies/app/model/FullTrigger.java
- src/main/java/com/redhat/cloud/custompolicies/app/model/Policy.java
- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
- src/main/resources/db/migration/V4.sql
- src/test/java/com/redhat/cloud/custompolicies/app/RestApiTest.java
- src/test/java/com/redhat/cloud/custompolicies/app/TestPolicy.java
- src/test/resources/db/migration/V999.sql
> Add code to update and delete policies.

- src/main/java/com/redhat/cloud/custompolicies/app/model/Policy.java
- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
(as it really is a string) and add some descriptions.
cc @zsadeh
> CPOL-60 Hide customerid in Json, mark mtime as String in openApi

- pom.xml
> Bump Quarkus to 1.2

- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
- src/test/java/com/redhat/cloud/custompolicies/app/RestApiTest.java
> CPOL-83 Return stored policy in response.

- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
> CPOL-94 Add missing schema entries.

- src/main/java/com/redhat/cloud/custompolicies/app/model/Policy.java
- src/main/java/com/redhat/cloud/custompolicies/app/model/pager/Pager.java
- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
- src/main/java/com/redhat/cloud/custompolicies/app/rest/utils/PagingUtils.java
- src/test/java/com/redhat/cloud/custompolicies/app/RestApiTest.java
- src/test/java/com/redhat/cloud/custompolicies/app/rest/utils/PagingUtilsTest.java
- src/test/resources/db/migration/V999.sql
This requires changes in the UI as well. 
> CPOL-84 implement paging according to platform standards.

- pom.xml
> Bump Quarkus to 1.2.1

- src/main/java/com/redhat/cloud/custompolicies/app/model/Policy.java
- src/main/java/com/redhat/cloud/custompolicies/app/model/pager/Pager.java
Empty Sort objects are now supported by quarkus
> Update sort usage

- src/main/java/com/redhat/cloud/custompolicies/app/VerifyEngine.java
- src/main/java/com/redhat/cloud/custompolicies/app/model/FullTrigger.java
- src/main/java/com/redhat/cloud/custompolicies/app/model/Policy.java
- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
- src/main/resources/db/migration/V1.sql
- src/main/resources/db/migration/V3.sql
- src/main/resources/db/migration/V4.sql
- src/test/java/com/redhat/cloud/custompolicies/app/RestApiTest.java
- src/test/java/com/redhat/cloud/custompolicies/app/TestPolicy.java
- src/test/resources/db/migration/V999.sql
Also use that UUID as trigger id.
WARNING: needs a re-set of the database. Migration is not incremental
This also needs some changes on the UI side.
> CPOL-92 Use a UUID as PK for Policies.

- src/main/java/com/redhat/cloud/custompolicies/app/auth/IncomingRequestFilter.java
- src/main/java/com/redhat/cloud/custompolicies/app/openapi/OASModifier.java
- src/main/resources/application.properties
cc @zsadeh
```
$ curl -i -HAccept:application/json  http://localhost:8080/api/custom-policies/v1.0/openapi.json
...
{
"openapi" : "3.0.1",
"info" : {
...
"paths" : {
"/facts" : {
"get" : {
"summary" : "Retrieve a list of fact (keys) along with their data types",
"operationId" : "GET_facts",
"responses" : {
"200" : {
...
```
> CPOL-106 provide the optional OperationID

- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
> CPOL-83 Provide return type in openapi spec.

- src/main/java/com/redhat/cloud/custompolicies/app/model/FullTrigger.java
- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
- src/test/java/com/redhat/cloud/custompolicies/app/RestApiTest.java
and Prevents NPE when policy.id is null.
> Fixes validate for new policies

- src/main/java/com/redhat/cloud/custompolicies/app/openapi/OASModifier.java
```
$ curl  http://localhost:8080/api/custom-policies/v1.0/openapi.json | grep operationId
operationId: getFacts
operationId: getPolicies
operationId: postPolicies
operationId: getPoliciesById
operationId: deletePoliciesById
operationId: putPoliciesByPolicyId
operationId: postPoliciesValidate
```
> CPOL-106 (followup) change operation id to be camelCase.

- src/main/java/com/redhat/cloud/custompolicies/app/JsonAccessLoggerHandler.java
- src/main/java/com/redhat/cloud/custompolicies/app/auth/IncomingRequestFilter.java
> CPOL-117 Log the account id of the requestor.

- src/main/java/com/redhat/cloud/custompolicies/app/VerifyEngine.java
- src/main/java/com/redhat/cloud/custompolicies/app/model/FullTrigger.java
- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
- src/test/java/com/redhat/cloud/custompolicies/app/RestApiTest.java
> CPOL-63 send actions to engine

- src/main/java/com/redhat/cloud/custompolicies/app/NotificationSystem.java
- src/main/java/com/redhat/cloud/custompolicies/app/auth/IncomingRequestFilter.java
- src/main/java/com/redhat/cloud/custompolicies/app/auth/RhIdPrincipal.java
- src/main/java/com/redhat/cloud/custompolicies/app/model/SettingsValues.java
- src/main/java/com/redhat/cloud/custompolicies/app/rest/SettingsService.java
- src/main/resources/application.properties
- src/main/resources/db/migration/V5.sql
- src/main/resources/settings-schema-template.json
- src/test/java/com/redhat/cloud/custompolicies/app/AbstractITest.java
- src/test/java/com/redhat/cloud/custompolicies/app/RestApiTest.java
- src/test/java/com/redhat/cloud/custompolicies/app/SettingsServiceTest.java
> CPOL-104 Implement endpoint for user email preferences

- src/main/java/com/redhat/cloud/custompolicies/app/model/FullTrigger.java
Update dataId to platform.inventory.host-egress to indicate the source
> CPOL-123 Update dataId

- src/main/java/com/redhat/cloud/custompolicies/app/rest/SettingsService.java
> Debug help for settings

- pom.xml
- src/main/java/com/redhat/cloud/custompolicies/app/model/Policy.java
- src/test/java/com/redhat/cloud/custompolicies/app/AbstractITest.java
- src/test/java/com/redhat/cloud/custompolicies/app/RestApiTest.java
- src/test/java/com/redhat/cloud/custompolicies/app/SettingsServiceTest.java
- src/test/java/com/redhat/cloud/custompolicies/app/TestLifecycleManager.java
This is part of the 'tracing' PR, just broken out.
- change testing as BeforeAll semantics has changed.
- Sort.toOrderBy was removed, so it is now a helper in Policy
> Bump Quarkus to 1.3

- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
> CPOL-130 If the engine does not have the policy, we can safely delete it

- pom.xml
- src/main/java/com/redhat/cloud/custompolicies/app/RbacServer.java
- src/main/java/com/redhat/cloud/custompolicies/app/auth/IncomingRequestFilter.java
- src/main/java/com/redhat/cloud/custompolicies/app/auth/RbacFilter.java
- src/main/java/com/redhat/cloud/custompolicies/app/auth/RhIdPrincipal.java
- src/main/java/com/redhat/cloud/custompolicies/app/model/Policy.java
- src/main/resources/application.properties
- src/test/java/com/redhat/cloud/custompolicies/app/AbstractITest.java
- src/test/java/com/redhat/cloud/custompolicies/app/RestApiTest.java
- src/test/java/com/redhat/cloud/custompolicies/app/SettingsServiceTest.java
- src/test/java/com/redhat/cloud/custompolicies/app/TestLifecycleManager.java
Depends on #62 (actually it includes it)
> CPOL-66 Rbac caching

- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
A schema generator was complaining about this.
Required for https://github.com/RedHatInsights/custom-policies-ui-frontend/pull/76
> Add missing schema.type to some parameters

- src/main/java/com/redhat/cloud/custompolicies/app/NotificationSystem.java
- src/main/java/com/redhat/cloud/custompolicies/app/rest/SettingsService.java
- src/main/resources/application.properties
- src/test/java/com/redhat/cloud/custompolicies/app/SettingsServiceTest.java
- src/test/java/com/redhat/cloud/custompolicies/app/TestLifecycleManager.java
Especially when notification system can't be reached.
cc @karelhala
> Harden settings service.

- src/main/java/com/redhat/cloud/custompolicies/app/rest/SettingsService.java
- src/test/java/com/redhat/cloud/custompolicies/app/SettingsServiceTest.java
mockup: https://marvelapp.com/5ha40i4/screen/67230839
// cc @karelhala
> CPOL-122 Switch back to user preferences and some UX changes

- .gitignore
- src/main/java/com/redhat/cloud/custompolicies/app/PolicyEngine.java
- src/main/java/com/redhat/cloud/custompolicies/app/model/engine/Condition.java
- src/main/java/com/redhat/cloud/custompolicies/app/model/engine/FullTrigger.java
- src/main/java/com/redhat/cloud/custompolicies/app/model/engine/Trigger.java
- src/main/java/com/redhat/cloud/custompolicies/app/model/engine/TriggerAction.java
- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
- src/test/java/com/redhat/cloud/custompolicies/app/FullTriggerHandlingTest.java
- src/test/java/com/redhat/cloud/custompolicies/app/RestApiTest.java
Fix the update logic.
There is one part of a test currently disabled, as this needs more work in the mockserver to correctly identify the policy and then reply with a correctly mocked FullTrigger for further processing.
> CPOL-63 (followup)

- src/main/java/com/redhat/cloud/custompolicies/app/PolicyEngine.java
- src/main/java/com/redhat/cloud/custompolicies/app/model/Policy.java
- src/main/java/com/redhat/cloud/custompolicies/app/model/engine/Condition.java
- src/main/java/com/redhat/cloud/custompolicies/app/model/engine/FullTrigger.java
- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
- src/test/java/com/redhat/cloud/custompolicies/app/RestApiTest.java
- src/test/java/com/redhat/cloud/custompolicies/app/TestPolicy.java
For this to work we need https://github.com/RedHatInsights/custom-policies-engine/pull/39 first.
Also it would be good if the engine could allow to batch retrieve the data (in a more compact way).
> CPOL-97 First implementation to show last triggered time.

- src/main/java/com/redhat/cloud/custompolicies/app/model/Policy.java
- src/main/java/com/redhat/cloud/custompolicies/app/model/engine/FullTrigger.java
- src/main/java/com/redhat/cloud/custompolicies/app/model/validation/ActionValidator.java
- src/main/java/com/redhat/cloud/custompolicies/app/model/validation/ValidActionS.java
- src/test/java/com/redhat/cloud/custompolicies/app/FullTriggerHandlingTest.java
- src/test/java/com/redhat/cloud/custompolicies/app/RestApiTest.java
> CPOL-146 Add validation for passed actions

- src/main/java/com/redhat/cloud/custompolicies/app/model/Policy.java
- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
- src/main/resources/db/migration/V6.sql
- src/test/java/com/redhat/cloud/custompolicies/app/RestApiTest.java
- src/test/java/com/redhat/cloud/custompolicies/app/TestPolicy.java
- Fix a bug in mtime handling as well.
> CPOL-102 Also provide policy create time.

- src/test/java/com/redhat/cloud/policies/app/model/filter/FilterTest.java
- src/test/java/com/redhat/cloud/policies/app/rest/utils/PagingUtilsTest.java
> Make those tests run.

- src/main/java/com/redhat/cloud/policies/app/RouteRedirector.java
> Move into app sub-package.

- src/main/java/com/redhat/cloud/policies/app/model/engine/FullTrigger.java
- src/test/java/com/redhat/cloud/policies/app/FullTriggerHandlingTest.java
> POL-171 Also update name and description, fix potential NPE.

- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/test/java/com/redhat/cloud/policies/app/RestApiTest.java
> POL-182 Change return code of DELETE policy from 400 to 404

- pom.xml
- src/main/resources/application.properties
- src/test/java/com/redhat/cloud/policies/app/SettingsServiceTest.java
- src/test/java/com/redhat/cloud/policies/app/TestLifecycleManager.java
> Enable setting test

- src/main/java/com/redhat/cloud/policies/app/PolicyEngine.java
- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/test/java/com/redhat/cloud/policies/app/RestApiTest.java
- src/test/java/com/redhat/cloud/policies/app/TestLifecycleManager.java
This uses the new engine functionality of https://github.com/RedHatInsights/policies-engine/pull/61
> Add an endpoint to enable/disable a policy

- src/main/java/com/redhat/cloud/policies/app/rest/FactService.java
- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/main/java/com/redhat/cloud/policies/app/rest/UserConfigService.java
- src/test/java/com/redhat/cloud/policies/app/TestLifecycleManager.java
- src/test/java/com/redhat/cloud/policies/app/UserConfigServiceTest.java
Also rename the Class + Test to better tell what it is doing.
> Change metrics to SimplyTimed, add for user-config.

- src/main/java/com/redhat/cloud/policies/app/rest/BasePathFillerService.java
- src/test/java/com/redhat/cloud/policies/app/BasePathTest.java
> POL-198 Return a 404 for '/api/policies/v1.0/'

- src/main/java/com/redhat/cloud/policies/app/EngineResponseExceptionMapper.java
- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/main/java/com/redhat/cloud/policies/app/rest/UserConfigService.java
- src/main/java/com/redhat/cloud/policies/app/rest/utils/PagingUtils.java
> Some smaller changes and fixes.

- src/main/java/com/redhat/cloud/policies/app/RouteRedirector.java
- src/main/java/com/redhat/cloud/policies/app/openapi/OASAcceptHeaderMangler.java
- src/test/java/com/redhat/cloud/policies/app/AbstractITest.java
- src/test/java/com/redhat/cloud/policies/app/BasePathTest.java
- src/test/java/com/redhat/cloud/policies/app/RestApiRedirectTest.java
- src/test/java/com/redhat/cloud/policies/app/RestApiTest.java
- src/test/java/com/redhat/cloud/policies/app/UserConfigServiceTest.java
This way we don't need to send a 307 redirect.
> POL-169 Change rewriting to Quarkus/Vert.X-internal.

- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/test/java/com/redhat/cloud/policies/app/RestApiTest.java
> POL-212 Update mtime on enable/disable.

- pom.xml
- src/main/java/com/redhat/cloud/policies/app/auth/IncomingRequestFilter.java
- src/main/java/com/redhat/cloud/policies/app/openapi/OASModifier.java
- src/main/java/com/redhat/cloud/policies/app/rest/BasePathFillerService.java
- src/main/resources/META-INF/openapi.json
- src/test/java/com/redhat/cloud/policies/app/OapiTest.java
Also add some general validation of the open api document.
Btw: technically an empty path element is valid: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#securityFiltering
> POL-215 - fix empty path

- src/main/java/com/redhat/cloud/policies/app/model/Policy.java
- src/main/java/com/redhat/cloud/policies/app/model/UUIDHelperBean.java
- src/main/java/com/redhat/cloud/policies/app/openapi/OASAcceptHeaderMangler.java
- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/main/resources/application.properties
- src/test/java/com/redhat/cloud/policies/app/RestApiTest.java
- src/test/java/com/redhat/cloud/policies/app/TestLifecycleManager.java
- src/test/java/com/redhat/cloud/policies/app/TestUUIDHelperBean.java
> POL-214 Don't store policy if engine reports an error.

- src/main/java/com/redhat/cloud/policies/app/EngineResponseExceptionMapper.java
- src/main/java/com/redhat/cloud/policies/app/model/Policy.java
- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/test/java/com/redhat/cloud/policies/app/AbstractITest.java
- src/test/java/com/redhat/cloud/policies/app/RestApiRedirectTest.java
- src/test/java/com/redhat/cloud/policies/app/RestApiTest.java
- src/test/java/com/redhat/cloud/policies/app/TestLifecycleManager.java
- src/test/resources/db/migration/V999.sql
- Provide policy ids after filtering.
> POL-175 Support for mass-operations

- pom.xml
- src/main/java/com/redhat/cloud/policies/app/auth/RbacFilter.java
> Bump Quarkus to 1.3.2 and add a span for getRbac

- src/main/java/com/redhat/cloud/policies/app/model/pager/Pager.java
- src/test/java/com/redhat/cloud/policies/app/RestApiTest.java
- src/test/java/com/redhat/cloud/policies/app/rest/utils/PagingUtilsTest.java
This follows the new default in the UI. 
@josejulio WDYT - should we leave as is or apply this change?
> Adjust the default page size to 50.

- src/main/java/com/redhat/cloud/policies/app/openapi/OASModifier.java
- src/main/java/com/redhat/cloud/policies/app/rest/UserConfigService.java
- src/test/java/com/redhat/cloud/policies/app/OapiTest.java
> POL-230 user-config is private. Don't show in OpenAPI

- pom.xml
> Downgrade OpenAPI parser to released version.

- pom.xml
- src/main/resources/application.properties
> Allow logging to Sentry.

- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/main/java/com/redhat/cloud/policies/app/rest/utils/PagingUtils.java
- src/test/java/com/redhat/cloud/policies/app/RestApiTest.java
- src/test/java/com/redhat/cloud/policies/app/rest/utils/PagingUtilsTest.java
> POL-270 Filter for enabled column is always BOOLEAN_IS

- src/main/java/com/redhat/cloud/policies/app/EngineResponseExceptionMapper.java
- src/main/java/com/redhat/cloud/policies/app/PolicyEngine.java
- src/main/java/com/redhat/cloud/policies/app/model/Policy.java
- src/main/java/com/redhat/cloud/policies/app/model/engine/Alert.java
- src/main/java/com/redhat/cloud/policies/app/model/engine/FullTrigger.java
- src/main/java/com/redhat/cloud/policies/app/model/engine/Trigger.java
- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/test/java/com/redhat/cloud/policies/app/RestApiTest.java
- src/test/java/com/redhat/cloud/policies/app/TestLifecycleManager.java
- src/test/java/com/redhat/cloud/policies/app/TestPolicy.java
> POL-226 Retrieve lastTriggered time from engine.

- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/test/java/com/redhat/cloud/policies/app/RestApiTest.java
- src/test/java/com/redhat/cloud/policies/app/TestLifecycleManager.java
> POL-283 Get latest trigger entry not the 1st in list.

- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
Removing `schema = @Schema(type = SchemaType.STRING)` from the `@Parameter` so it uses the actual type of the `@PathParam` (`UUID` instead of `String`)
> Small cleanup

- pom.xml
- src/main/java/com/redhat/cloud/policies/app/EngineResponseExceptionMapper.java
> Bump Quarkus to 1.5.1.

- src/main/java/com/redhat/cloud/policies/app/model/Policy.java
- src/main/java/com/redhat/cloud/policies/app/rest/utils/PagingUtils.java
- src/test/java/com/redhat/cloud/policies/app/RestApiTest.java
- Use range paging
- Fix a bug on last page when the total is divisible by the limit
> Changes on policy paging

- pom.xml
The previous one #122 unfortunately only bumped to CR1
> Bump to Quarkus 1.6.0.Final

- pom.xml
- src/main/java/com/redhat/cloud/policies/app/PolicyEngine.java
- src/main/java/com/redhat/cloud/policies/app/model/filter/Filter.java
- src/main/java/com/redhat/cloud/policies/app/model/filter/PolicyHistoryTagFilterHelper.java
- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/test/java/com/redhat/cloud/policies/app/RestApiTest.java
- src/test/java/com/redhat/cloud/policies/app/TestLifecycleManager.java
- src/test/java/com/redhat/cloud/policies/app/model/filter/TagsFilterTest.java
- src/test/resources/alerts-history.json
- src/test/resources/alerts-history2.json
- src/test/resources/alerts-history3.json
Now that POL-314 is in the engine, filtering on the history can be done.
> POL-301 policy history filter

- src/main/java/com/redhat/cloud/policies/app/model/filter/PolicyHistoryTagFilterHelper.java
- src/test/java/com/redhat/cloud/policies/app/model/filter/TagsFilterTest.java
The engine parser doesn't like them.
> Remove parentheses around tag query conditions

- pom.xml
- src/main/java/com/redhat/cloud/policies/app/health/ProcSelfStatusExporter.java
Expose some of the metrics that the OS sees via MP-Metrics
> Expose metrics from /proc/self/status via MP-Metrics.

- src/main/java/com/redhat/cloud/policies/app/model/engine/Condition.java
- src/main/java/com/redhat/cloud/policies/app/rest/utils/PagingUtils.java
- src/test/java/com/redhat/cloud/policies/app/RestApiTest.java
- src/test/java/com/redhat/cloud/policies/app/rest/utils/PagingUtilsTest.java
This applies to the list of policies and the policy history
> POL-330 Honor sort order if no column is explicitly given.

- helpers/create_manifest.sh
- manifest.txt
- pom.xml
The manifest file is created during maven install
and needs to manually committed when changes are made.
> Create a manifest, that lists dependencies.

- src/main/java/com/redhat/cloud/policies/app/NotificationSystem.java
- src/main/java/com/redhat/cloud/policies/app/auth/IncomingRequestFilter.java
- src/main/java/com/redhat/cloud/policies/app/auth/RbacFilter.java
- src/main/java/com/redhat/cloud/policies/app/health/StatusEndpoint.java
Example for "nothing works":
```
$ curl -i  http://localhost:8080/api/policies/v1.0/status
HTTP/1.1 500 Internal Server Error
Content-Length: 440
Content-Type: text/plain;charset=UTF-8
[org.hibernate.exception.JDBCConnectionException: Unable to release JDBC Connection, RESTEASY004655: Unable to invoke request: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8084 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused), RESTEASY004655: Unable to invoke request: java.net.UnknownHostException: policies-notifications: nodename nor servname provided, or not known]
```
> POL-331 Provide a /status endpoint.

- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
Josejulio can you check if that has any bad implications for the UI?
At least Swagger-UI is more happy now
> POL-287 Make the OpenAPI return type more specific than just 'list'

- src/main/java/com/redhat/cloud/policies/app/model/Msg.java
- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- Before it was an anynymous object in the response
> Move "Msg" to components section

- src/main/java/com/redhat/cloud/policies/app/model/filter/PolicyHistoryTagFilterHelper.java
- src/test/java/com/redhat/cloud/policies/app/TestLifecycleManager.java
- src/test/java/com/redhat/cloud/policies/app/model/filter/TagsFilterTest.java
Depends on https://github.com/RedHatInsights/policies-engine/pull/29
> Update tag query

- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/test/java/com/redhat/cloud/policies/app/AlertHistoryParserTest.java
- src/test/resources/alerts-history.json
- src/test/resources/alerts-history2.json
- src/test/resources/alerts-history3.json
The way the engine emits tags has changed in https://github.com/RedHatInsights/policies-engine/pull/110 so we need to follow up.
> Follow the tag format change from the engine.

- src/main/java/com/redhat/cloud/policies/app/StuffHolder.java
- src/main/java/com/redhat/cloud/policies/app/auth/RhIdPrincipalProducer.java
- src/main/java/com/redhat/cloud/policies/app/health/ScheduledStatusProducer.java
- src/main/java/com/redhat/cloud/policies/app/health/StatusEndpoint.java
- src/main/java/com/redhat/cloud/policies/app/rest/AdminService.java
- src/test/java/com/redhat/cloud/policies/app/StatusEndpointTest.java
> Fix issue with CDI scopes resulting in wrong metric result.

- pom.xml
This needs the corresponding e2e pr first.
> Add a SonarQube scan profile

- .rhcicd/grafana-dashboard-insights-policies.configmap.yaml
change the dashaboard name in the grafana configMap.
> change the dashaboard name in the grafana configMap.

- .rhcicd/grafana-dashboard-insights-policies.configmap.yaml
[NOTIF-185] Manually update the dashboard configuration.
>  [NOTIF-185] Manually update the dashboard configuration.

- src/main/resources/db/migration/V9.0.1__POL-447_POL-468-add-facts.sql
- facts.installed_packages_delta
- facts.cpu_model
- facts.dnf_modules
- facts.operating_system
> POL-447 POL-468 Add new facts

- src/main/java/com/redhat/cloud/policies/app/model/history/PoliciesHistoryRepository.java
- src/test/java/com/redhat/cloud/policies/app/PolicyCrudServiceTest.java
This fixes an offset issue I noticed during tests on stage today.
> POL-450 Fix offset in policies-history queries

- .github/workflows/build.yml
Same as https://github.com/RedHatInsights/notifications-backend/pull/494.
> Improve build.yml

- .github/workflows/build.yml
- .rhcicd/build_deploy.sh
- .rhcicd/clowdapp.yaml
- .rhcicd/pr_check.sh
- src/main/docker/Dockerfile.jvm
- src/main/java/com/redhat/cloud/policies/app/ClowderConfigInitializer.java
Depends on [app-interface!28292](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/28292).
> POL-543 Clowderize pr_check.sh

- src/main/java/com/redhat/cloud/policies/app/EnvironmentFlags.java
- src/main/java/com/redhat/cloud/policies/app/model/validation/ActionValidator.java
- src/main/java/com/redhat/cloud/policies/app/rest/UserConfigService.java
- src/test/java/com/redhat/cloud/policies/app/UserConfigServiceTest.java
- src/test/java/com/redhat/cloud/policies/app/model/validation/ActionValidatorTest.java
~Missing to test with policies-ui-frontend and see how it behaves~
> POL-601 Limit some features on fedramp

- src/main/docker/Dockerfile.jvm
> Stop dumping the heap on OutOfMemoryError

- .rhcicd/clowdapp.yaml
- src/main/resources/db/migration/V11__POL-616_policies_db_cleaner.sql
- src/test/java/com/redhat/cloud/policies/app/PoliciesHistoryCleanerTest.java
Similar to https://github.com/RedHatInsights/notifications-backend/pull/815 which is already running on prod.
> POL-616 Run the DB cleaning job from a CronJob - Phase 1

- sonar-project.properties
I tried to add this project under the QE cron job for soanrqube analysis collection.
I found the project has some java binaries itself so adding root path as the binary path.
> SonarQube properties

- src/main/resources/db/migration/V14__POL-593-adding-ansible-facts.sql
> POL-593 Adding ansible facts

- src/main/java/com/redhat/cloud/policies/app/auth/RbacFilter.java
> Allow to disable RBAC for local testing

- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
Prod is unstable and the current code is hiding the real issue behind a `Connection to backend-engine failed. Please retry later` message.
> Log exceptions cause and stack trace

- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
This should fix the following error on stage:
> POL-649 Return policy in store response

- .github/workflows/checkupdate.yml
WDYT of making this small change to reflect exactly what the PR does?
> Change PR and commit messages of ubi-minimal updates

- .rhcicd/clowdapp.yaml
- .rhcicd/run_org_id_populator.yaml
Had to open the PR once again: https://github.com/RedHatInsights/policies-ui-backend/pull/434
> POL-650 Add org-id-populator jobs

- src/main/java/com/redhat/cloud/policies/app/rest/utils/PagingUtils.java
- src/test/java/com/redhat/cloud/policies/app/RestApiTest.java
Only empty, true, false should be accepted.
> POL-644 Reject bad values for booleans.

- pom.xml
- src/main/java/com/redhat/cloud/policies/app/health/ProcSelfStatusExporter.java
- src/main/java/com/redhat/cloud/policies/app/health/ScheduledStatusProducer.java
- src/main/java/com/redhat/cloud/policies/app/rest/FactService.java
- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/main/java/com/redhat/cloud/policies/app/rest/UserConfigService.java
- src/test/java/com/redhat/cloud/policies/app/StatusEndpointTest.java
- src/test/java/com/redhat/cloud/policies/app/model/validation/ActionValidatorTest.java
Added things from here: https://github.com/RedHatInsights/policies-ui-backend/pull/362
> POL-595 Use micrometer metrics

- .rhcicd/build_deploy.sh
Adding conditional logic to the build deploy script for the security compliance branch.
> Adding conditional to build deploy script in security compliance branch

- src/main/resources/db/migration/V24__DRFT-1361_add_systemd_fact.sql
This PR addresses: [DRFT-1361](https://issues.redhat.com/browse/DRFT-1361)
> feat(DRFT-1361): Add systemd fact to policies

- pom.xml
- src/test/java/com/redhat/cloud/policies/app/PoliciesLastTriggeredTest.java
- src/test/java/com/redhat/cloud/policies/app/PolicyCrudServiceTest.java
Fixes database cleanup on some selective tests.
(Hopefully) fixes JaCoCo configuration and coverage of integration tests.
Exclusion of integration tests is lifted.
> fix(tests): integration tests run

- .rhcicd/build_deploy.sh
Pushed to wrong branch
Reverts RedHatInsights/policies-ui-backend#574
> Revert "Removing wildcard from SC Branch Build Check "

- pom.xml
to fix rapid reset https://github.com/netty/netty/security/advisories/GHSA-xpw8-rcwv-8f8p
RHINENG-2516
> fix: upgrade netty-codec-http2

- pom.xml
to get backported fixes
RHINENG-1489
> chore: upgrade okio dependency

- src/main/java/com/redhat/cloud/policies/app/auth/RbacFilter.java
> fix: ConfigProperty injection w/ Instance

- .rhcicd/clowdapp.yaml
> fix: sentry dns templated

- pom.xml
> chore(pom): consolidate and update packages

- src/main/java/com/redhat/cloud/policies/app/rest/utils/PagingUtils.java
> fix: improve filter query matcher

- src/main/java/com/redhat/cloud/policies/app/rest/AdminService.java
- src/test/java/com/redhat/cloud/policies/app/AdminServiceTest.java
> fix: internal api

- .rhcicd/clowdapp.yaml
This PR adds data export to the HMS bucket for analytics.
RHINENG-9419
/ping @vkrizan @skateman
> Add HMS floor plan export

- .dockerignore
- .rhcicd/build_deploy.sh
> ci: temp dir for docker

- pom.xml
> chore: update Quarkus platform

- src/test/java/com/redhat/cloud/policies/app/TestLifecycleManager.java
Fixes test runs with testcontainers with podman by specifying the image with repository.
> fix(tests): use specific postgres container image

- .rhcicd/clowdapp.yaml
> feat(clowder): pull container image from konflux quay

- .github/workflows/checkupdate.yml
- src/main/docker/Dockerfile.jvm
RHINENG-13893
Please merge only when Konflux supports UBI8 (Monday 28th of Oct).
> Revert to UBI8 images

- pom.xml
> Updates commons-io

- .rhcicd/clowdapp.yaml
This change is implementing changes recommended by 'Trusted Resource Configuration (ADR-46) Implementation' to limit CPU/MEM requests/limits in ephemeral environment.
> Change CPU/MEMORY limits for clowdapp - ADR46

- pom.xml
Update quarkus version to the latest Red Hat releases
> RHINENG-16637: Update quarkus version
