RedHatInsights/policies-ui-backend

- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
Given https://github.com/RedHatInsights/custom-policies-ui-frontend/pull/9 we can omit the CORs setup for now, as we are not likely needing it. 
This will save us the care of adding it to every new request.
In case we need it, I think we can setup it as shown here: https://quarkus.io/guides/http-reference#cors-filter
> Remove CORS calls

- pom.xml
- src/main/java/com/redhat/cloud/custompolicies/app/auth/IncomingRequestFilter.java
Get rid of a warning from Quarkus about access level
> Bump Quarkus to 1.1.0.Final.

- src/main/resources/application.properties
That seems to fix the openapi.json file to be served from the right URL
> Fixed openapi.json URL according to the standardized location

- src/test/java/com/redhat/cloud/custompolicies/app/RestApiTest.java
> Ensure that the openapi document is served at the right place.

- README.adoc
- src/main/java/com/redhat/cloud/custompolicies/app/auth/IncomingRequestFilter.java
- src/main/java/com/redhat/cloud/custompolicies/app/auth/RhIdPrincipal.java
- src/main/java/com/redhat/cloud/custompolicies/app/auth/RhIdPrincipalProducer.java
- src/main/java/com/redhat/cloud/custompolicies/app/auth/RhIdSecurityContext.java
- src/main/java/com/redhat/cloud/custompolicies/app/model/Policy.java
- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
- src/test/java/com/redhat/cloud/custompolicies/app/RestApiTest.java
- src/test/java/com/redhat/cloud/custompolicies/app/TestPolicy.java
- src/test/sql/dbinit.sql
Customeids in urls was an early stop-gap that allowed to select policy sets for different users.
Now that the id is supplied via x-rh-identity header, we can remove it.
https://issues.redhat.com/browse/CPOL-32
@zsadeh
> CPOL-32 Remove customerid from urls

- src/main/java/com/redhat/cloud/custompolicies/app/JaxRsApplication.java
- src/main/java/com/redhat/cloud/custompolicies/app/JsonAccessLoggerHandler.java
Output looks like 
`{"date":"Tue, 17 Dec 2019 15:31:03 GMT","method":"GET","uri":"/api/custom-policies/v1.0/facts","http_version":"HTTP/1.1","status":401,"content_length":0,"duration":83,"user_agent":"curl/7.54.0","remote":"0:0:0:0:0:0:0:1"}
`
> Produce a structured access log (goes to stdout).

- src/main/java/com/redhat/cloud/custompolicies/app/VerifyEngine.java
- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
- src/main/resources/application.properties
- src/test/java/com/redhat/cloud/custompolicies/app/RestApiTest.java
Also introduces a flag to skip the engine calls.
Mostly meant for local development.
> Actually send the policy to the engine when it is to be stored.

- src/main/java/com/redhat/cloud/custompolicies/app/model/FullTrigger.java
- The engine expects a Trigger with an ID. It documents
that when none is provided it will use an UUID, to
ensure consistency (because we do two calls, one to
validate and the later to store) create one UUID and
assign it to the ID of the Trigger.
> CPOL-49 Generate an id (Trigger) before engine validation

- src/main/java/com/redhat/cloud/custompolicies/app/JaxRsApplication.java
- src/main/java/com/redhat/cloud/custompolicies/app/JsonAccessLoggerHandler.java
- src/main/resources/application.properties
They happen very often in Kube and don't provide real value (in the logs) when they are successful.
If they do not return a 200 status, they are still logged. A property `accesslog.filter.health` can be set to false to prevent that filtering.
> Filter out calls to health and metrics in access log.

- src/main/java/com/redhat/cloud/custompolicies/app/openapi/OAPathModifier.java
- src/main/resources/META-INF/openapi.json
- src/main/resources/application.properties
This removes the `/api/custom-policies/v1.0` from the paths entries so that the output now looks like
```
security:
- Basic_auth: []
paths:
/facts:
get:
summary: Retrieve a list of fact (keys) along with their data types
```
cc @zsadeh
> CPOL-61 Reduce the path in the openapi document to the last url segment

- pom.xml
- src/main/java/com/redhat/cloud/custompolicies/RouteRedirector.java
Note that curl does not automatically follow the redirect and needs option `-L`:
```
$ curl -i -L  -Hx-rh-identity:`cat src/test/resources/rhid.txt` http://localhost:8080/api/custom-policies/v1/policies
HTTP/1.1 307 Temporary Redirect
Location: /api/custom-policies/v1.0/policies
content-length: 0
HTTP/1.1 200 OK
TotalCount: 1
Content-Length: 240
ETag: "14482333"
Content-Type: application/json
[{"id":101,"actions":"EMAIL toor@root.org","conditions":"rhelversion >= 8 OR cores = 5","description":"Another test","isEnabled":true,"mtime":"2020-01-24 12:19:56.718","name":"3rd policy","triggerId":"09875330-a547-4fb5-be70-0a544b6e2874"}]
```
cc @zsadeh
> CPOL-85 Redirect /api/../v1/ to /api/../v1.0/

- src/main/java/com/redhat/cloud/custompolicies/app/rest/PolicyCrudService.java
Now:
```
application_PolicyCrudService_getPoliciesForCustomer_min_seconds 0.016811467
application_PolicyCrudService_getPoliciesForCustomer_max_seconds 0.305149386
application_PolicyCrudService_getPoliciesForCustomer_mean_seconds 0.08556680147861713
```
> Shorten metric names. Prefix path is not needed.

- src/main/resources/db/migration/V1.sql
- src/test/resources/db/migration/V999.sql
Our user does not have enough rights in the DB.
And it was only used in tests, so remove and use
explicit uuids.
> CPOL-92 Don't try to install the UUID extension.

- src/main/java/com/redhat/cloud/custompolicies/app/openapi/OASAcceptHeaderMangler.java
```
$ curl -i  http://localhost:8080/api/custom-policies/v1.0/openapi.json 
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, HEAD, OPTIONS
Access-Control-Allow-Headers: Content-Type, Authorization
Access-Control-Max-Age: 86400
Content-Type: application/json;charset=UTF-8
content-length: 15066
{
"openapi" : "3.0.1",
"info" : {
"title" : "Custom-Policies",
"description" : "The API for Custom-Policies",
"version" : "1.0"
},
"servers" : [ {
```
> CPOL-107 If user requests openapi.json, then send json.

- helpers/docker-compose.yaml
- pom.xml
- src/main/java/com/redhat/cloud/custompolicies/app/auth/IncomingRequestFilter.java
- src/main/java/com/redhat/cloud/custompolicies/app/auth/RbacFilter.java
- src/main/resources/application.properties
- src/test/java/com/redhat/cloud/custompolicies/app/SettingsServiceTest.java
- src/test/java/com/redhat/cloud/custompolicies/app/TestLifecycleManager.java
This is a larger change. I tried this with Quarkus 1.2 but failed (most likely pilot error), so I pulled in 1.3 where I got it to work.
- bump Quarkus to 1.3.0.Final
+- Change test setup to use QuarkusTestResource
- Pull in MP-OpenTracing and set it up in application.properties.
- Separate out Rbac retrieval from IncomingRequestFilter, as otherwise it would not be part of the outer span (that only starts when the endpoint is hit, but the IRF is a @PreMatch filter, which runs before
- Implement a Rbac cache: This is a simple annotation that creates the cache. Entries expire after 2mins (see application.properties) 
With engine also instrumented :
See also https://github.com/RedHatInsights/custom-policies-engine/pull/42
> Add support for distributed tracing

- helpers/docker-compose.yaml
Looks like the POSTGRES_PASSWORD is now mandatory:
```
Attaching to helpers_zookeeper_1, helpers_postgres_1, helpers_kafka_1, helpers_jaeger_1
postgres_1   | Error: Database is uninitialized and superuser password is not specified.
postgres_1   |        You must specify POSTGRES_PASSWORD to a non-empty value for the
postgres_1   |        superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
postgres_1   | 
postgres_1   |        You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
postgres_1   |        connections without a password. This is *not* recommended.
postgres_1   | 
postgres_1   |        See PostgreSQL documentation about "trust":
postgres_1   |        https://www.postgresql.org/docs/current/auth-trust.html
helpers_postgres_1 exited with code 1
``` …
> Add default password to helper's postgres container

- src/main/java/com/redhat/cloud/policies/app/model/Policy.java
- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
Prevents having to parse stuff like "1969-12-31 18:00:00.0" as "not set"
> POL-97 Sets lastEvaluation to empty when 0

- pom.xml
- src/main/resources/application.properties
I have no idea if there is a need for a jdbc driver change in the DC when this is installed or not.
There is certainly a change in application.properties respective to 1.3.0 for the case of tests.
> Bump Quarkus to 1.3.1

- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/main/resources/application.properties
This way the user on the UI does not need to wait for too long if they are in a odd state.
Before this change if you Ctrl-Z the engine, and then refresh the list or click on store in the create-wizard, it would hang "forever". With this change, the rest-request to engine, rbac and notifications is aborted after ~2s and the user either gets a nice error message or in case of list view, the list is shown, but data like lastEvaluated (lastTriggered in the future) will be omitted.
cc @hsagman -- this is something we talked about yesterday
> Introduce explicit timeouts for calls to other services.

- src/main/java/com/redhat/cloud/policies/app/model/Policy.java
- src/test/java/com/redhat/cloud/policies/app/RestApiTest.java
Also guards the API calls for adding or editing policies with long names.
> POL-207 Limit Policy.name to 150 characters

- src/main/java/com/redhat/cloud/policies/app/JaxRsApplication.java
- src/main/java/com/redhat/cloud/policies/app/TokenHolder.java
- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
PoC of a service, that gets all Policies from the DB, checks if they exist in the engine and if not,
stores them in the engine.
When the app starts, a token is emitted in the logs. This token needs to be given on the URL for the mechanism to work. Also it currently requires a valid rh-identity.
Currently it does not try to sync entries that are different in postgres and engine.
Ideally we would be able to block the endpoint in 3scale.
> PoC: Sync down policies into the engine.

- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/test/java/com/redhat/cloud/policies/app/RestApiTest.java
The frontend is encoding the content as a json, so `ABC` becomes `"ABC"`, but the backend is not honoring the `Content-Type` and taking the plain json string.
This fixes that call and makes the method to specifically expect a `JsonString`.
> POL-241 Ensure validate-name decodes string from json

- pom.xml
- src/main/java/com/redhat/cloud/policies/app/PolicyEngine.java
- src/main/java/com/redhat/cloud/policies/app/model/engine/HistoryItem.java
- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/test/java/com/redhat/cloud/policies/app/RestApiTest.java
- src/test/java/com/redhat/cloud/policies/app/TestLifecycleManager.java
- src/test/resources/alerts-history.json
```
$ curl -i -Hx-rh-identity:`cat rhid.txt` http://localhost:8080/api/policies/v1.0/policies/8671900e-9d31-47bf-9249-8f45698ede72/history/trigger
HTTP/1.1 200 OK
Content-Length: 1711
Content-Type: application/json
[{"ctime":1590506001593,"hostName":"VM 22","id":"d4039530-4e3c-dead-beef-44de55400c2b"},
{"ctime":1590506001553,"hostName":"VM 22","id":"d4039530-4e3c-dead-beef-44de55400c2b"},
{"ctime":1590506001551,"hostName":"VM 22","id":"d4039530-4e3c-dead-beef-44de55400c2b"},
{"ctime":1590506001551,"hostName":"VM 22","id":"d4039530-4e3c-dead-beef-44de55400c2b"},
{"ctime":1590506001550,"hostName":"VM 22","id":"d4039530-4e3c-dead-beef-44de55400c2b"}]
```
> [POL-282] Provide history items for one policy

- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/test/java/com/redhat/cloud/policies/app/RestApiTest.java
- src/test/resources/alerts-history.json
Using the `inventory_id` (`id` of the host used by the inventory) instead of the `insights_id`. 
Depends on https://github.com/RedHatInsights/policies-engine/pull/78 (merged)
> Use inventory_id instead of insights_id for the trigger history

- src/main/java/com/redhat/cloud/policies/app/PolicyEngine.java
- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/main/java/com/redhat/cloud/policies/app/rest/utils/PagingUtils.java
- src/test/java/com/redhat/cloud/policies/app/RestApiTest.java
- src/test/java/com/redhat/cloud/policies/app/TestLifecycleManager.java
> POL-293 Add paging to the history of a single policy

- src/main/java/com/redhat/cloud/policies/app/auth/RbacFilter.java
- src/main/resources/application.properties
Setting the property `warn.rbac.slow` to `false` turns the warnings off.
cc @lahavyuv86
> Warn if calls to RBAC take more than 500ms. Can be turned off.

- pom.xml
- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/test/java/com/redhat/cloud/policies/app/OapiTest.java
The quarkus upgrade removes from the openapi the EntityManager related fields.
> Upgrading to Quarkus 1.8.1 and adding few more types

- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/test/java/com/redhat/cloud/policies/app/RestApiTest.java
As previously discussed.
Question: should we silently do this. Or return some 400 for 'unknown sort field'?
The latter makes it probably more obvious for customers.
> POL-363 Don't sort the trigger history by id.

- src/main/java/com/redhat/cloud/policies/app/JaxRsApplication.java
- src/main/java/com/redhat/cloud/policies/app/StuffHolder.java
- src/main/java/com/redhat/cloud/policies/app/auth/IncomingRequestFilter.java
- src/main/java/com/redhat/cloud/policies/app/auth/RbacFilter.java
- src/main/java/com/redhat/cloud/policies/app/health/AbstractHealthCheck.java
- src/main/java/com/redhat/cloud/policies/app/health/LivenessProbe.java
- src/main/java/com/redhat/cloud/policies/app/health/StatusEndpoint.java
- src/main/java/com/redhat/cloud/policies/app/openapi/OASModifier.java
- src/main/java/com/redhat/cloud/policies/app/rest/AdminService.java
- src/main/java/com/redhat/cloud/policies/app/rest/FactService.java
- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/main/java/com/redhat/cloud/policies/app/rest/UserConfigService.java
- src/test/java/com/redhat/cloud/policies/app/HealthCheckTest.java
- src/test/java/com/redhat/cloud/policies/app/StatusEndpointTest.java
- src/test/java/com/redhat/cloud/policies/app/TestLifecycleManager.java
Also move the sync endpoint to /admin.
Adds a live check that can be set to fail.
```
$ curl -i -X POST    http://localhost:8080/admin/status?status=degraded
{"msg":"Set degraded state"}
$curl http://localhost:8080/status
HTTP/1.1 500 Internal Server Error
Content-Length: 287
Content-Type: text/plain;charset=UTF-8
{
engine=RESTEASY004655: Unable ...,
admin-degraded=true,
notifications=Unknown error, status code 401
}
$ curl -i  http://localhost:8080/health/live
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 121
{
"status": "UP",
"checks": [
{
"name": "live",
"status": "UP"
}
]
}
$ curl -i -X POST    http://localhost:8080/admin/status?status=admin-down
HTTP/1.1 200 OK
Content-Length: 30
Content-Type: application/json
{"msg":"Set admin down state"}
$curl …
```
> Start of an admin endpoint at /admin.

- src/main/java/com/redhat/cloud/policies/app/PolicyEngine.java
- src/main/java/com/redhat/cloud/policies/app/rest/AdminService.java
The 2nd part that looks at triggers in engine and then tries to find corresponding policies currently depends on accounts being in postgres, so that getTriggersForAccount() works. This needs to be improved going forward.
> Add a /verify endpoint to find orphaned entries.

- src/main/java/com/redhat/cloud/policies/app/rest/AdminService.java
- src/main/resources/application.properties
Property `stats.filter.cid` can be used to  filter out certain customerIds. That is a comma separated list.
Example:
$ curl -i  http://localhost:8080/admin/stats
HTTP/1.1 200 OK
Content-Length: 188
Content-Type: application/json
{"totalPoliciesCount":28,"filteredPoliciesCount":6,"customerIdsCount":4,"customerPoliciesCount":22,"buckets":{"1":1,"2":0,"3":1,"4":0,"10+":1,"5-10":2},"filteredIdsCount":1,"totalCount":5}
> More detailed stats that show a distribution of policies per customer.

- src/main/java/com/redhat/cloud/policies/app/health/StatusEndpoint.java
- src/main/java/com/redhat/cloud/policies/app/rest/AdminService.java
- src/test/java/com/redhat/cloud/policies/app/StatusEndpointTest.java
If degraded, log probe results as severe.
Due to the way Quarkus initialises things, the metric is only available after the first call to the status endpoint.
```
$ curl localhost:8080/api/policies/v1.0/status
{"engine":"RESTEASY004655: Unable to invoke request: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8084 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)","notifications":"Unknown error, status code 401"}
```
Logs then:
`2020-11-11 11:12:40,595 SEVERE [StatusEndpoint] (vert.x-worker-thread-4) Status reports: engine=RESTEASY004655: Unable to invoke request: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8084 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection …
> Expose status also as Gauge.

- src/main/resources/application.properties
We make the pool close connections after 60s to force creating a new connection, which makes the health check react on a  changed password.
How to test: start postgres with normal credentials, start ui-backend. Then in a terminal connect to postgres and issue e.g. 
`postgres=# alter user postgres password 'pg';`
Watch quarkus console. after ~ 60sec an error message should show about bad password when talking to postgres. Then do
`$ curl -i localhost:8080/health` or `curl -i localhost:8080/health/live` which should show the status as down and give a 5xx error.
```
$ curl localhost:8080/health
{
"status": "DOWN",
"checks": [
{
"name": "live",
"status": "UP"
},
{
"name": "Database connections health check",
"status": "DOWN",
"data": {
"default": "Unable to execute the validation check for …
```
> [POL-386] Make health check fail if there is a DB connection issue

- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- Persisted objects will save automatically, to prevent this
a RuntimeException should happen between the Transaction or
manually opt-in for a rollback via TransactionManager
> POL-432 Rollback database changes if any error happened.

- .github/workflows/main.yml
@pilhuhn I'm not really sure what changed, but with the changes in #101 `mvn package` is not running the same tests that `mvn install` does. 
I noticed because the `target/openapi.json` no longer appears when running `mvn package`.
Also, running locally, a bunch of logs appears on `install` that do not show on `package`.
> Run `mvn install` of `mvn package` on ci

- src/main/java/com/redhat/cloud/policies/app/JsonAccessLoggerHandler.java
> Metrics and Health are now under /q. Skip them in logs.

- helpers/docker-compose.yaml
- pom.xml
Also fix postgres version at 12 in docker-compose.yaml
Bump testcontainers to 1.15.1 to follow change in DockerHub API.
Explicitly add Jetbrains annotations as a test dep.
> Bump Quarkus to 1.11.2

- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
Logs this (or the enabled version depending on the conf) at startup:
```
2021-07-28T08:13:54.2286408Z 2021-07-28 08:13:54,227 INFO  [PolicyCrudService_Subclass] (main) Policies history is disabled. The history data will be retrieved from Infinispan.
```
Policies-history is still disabled by default.
> POL-450 Log policies-history state at startup

- src/main/java/com/redhat/cloud/policies/app/PoliciesHistoryCleaner.java
- src/main/resources/application.properties
- src/test/java/com/redhat/cloud/policies/app/PoliciesHistoryCleanerTest.java
The default history retention delay is 14 days. It can be changed with the `policies-history.cleaner.delete-after` conf property which accepts a `Duration` value compatible with the ISO-8601 duration format `PnDTnHnMn.nS`.
The scheduled job execution time doesn't really matter so I scheduled it with the `policies-history.cleaner.period` property which also accepts a `Duration` value. The default value is `P1D` which means once a day.
> POL-450 Clean old policies history entries

- pom.xml
- src/main/java/com/redhat/cloud/policies/app/auth/RbacFilter.java
- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/main/resources/application.properties
- src/test/java/com/redhat/cloud/policies/app/NonApplicationRootPathTest.java
The Quarkus path change is documented [here](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0#legacy-redirect-for-non-application-endpoints-such-as-health). The doc is not accurate though: `/health` and `/metrics` work without declaring an absolute path.
Opentracing changes are documented [here](https://github.com/opentracing/opentracing-java/blob/master/CHANGELOG.md#v0330-2019-05-06).
> POL-559 Bump Quarkus to 2.1.3.Final

- src/main/resources/application.properties
~Quarkus uses `PostgreSQL10Dialect` (the latest available) by default if no dialect is specified in `application.properties`.~
I'm not entirely sure the Quarkus magic works well with `io.opentracing.contrib.jdbc.TracingDriver` so let's use an explicit dialect for now.
> Change datasource dialect to PostgreSQL10Dialect

- src/main/resources/application.properties
`PostgreSQL10Dialect` is suspected to cause a memory leak. Let's see how it goes with this one.
> Downgrade Postgres dialect to PostgreSQL82Dialect

- .rhcicd/clowdapp.yaml
This is necessary to fix an IQE test failure.
> POL-543 Add RBAC_READ_TIMEOUT param in clowdapp.yaml

- src/main/java/com/redhat/cloud/policies/app/model/history/PoliciesHistoryRepository.java
- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/test/java/com/redhat/cloud/policies/app/RestApiTest.java
I suspect the memory issue we had for a while was not caused by a memory leak but rather by huge triggers lifecycle data returned by the engine when we need to retrieve the last trigger time.
After this PR, ui-backend will no longer retrieve any "last trigger time" from the engine.
Whether my hypothesis is right or not, this will be an improvement anyway.
> POL-570 Load last trigger time from Postgres

- src/main/java/com/redhat/cloud/policies/app/PoliciesHistoryCleaner.java
The initial run of `PoliciesHistoryCleaner` is currently happening too soon at application startup. It could overlap with a DB migration.
> Delay the initial PoliciesHistoryCleaner run

- .rhcicd/clowdapp.yaml
Policies-ui-backend needs this to be deployed on fedramp-stage.
> POL-621 Make the notifications-backend Clowder dependency optional

- .rhcicd/clowdapp.yaml
Fixes
```
11:47:34 2022-01-25 10:47:34 [    INFO] [           pid-26005]  |stderr| W0125 10:47:34.765681   26005 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
```
The first PR check run may fail because of an unrelated transitive dependency issue which is about to be fixed by the ingress team.
> Fix deprecated CronJob apiVersion

- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
This will show us how many times each `policies-ui-backend` REST endpoint is called and by who.
> Add temp counters to investigate an engine instability

- src/main/java/com/redhat/cloud/policies/app/lightweight/LightweightEngine.java
- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
Related to https://github.com/RedHatInsights/policies-engine/pull/379.
When an invalid condition is validated on stage with the lightweight engine, the validation error message isn't forwarded to the browser. This is the second half of the fix.
> POL-649 Return condition validation error in REST response

- .rhcicd/clowdapp.yaml
Related to https://github.com/RedHatInsights/policies-engine/pull/394.
Metrics show that the current CPU request and limit are way above the actual CPU used by the containers on prod.
> Decrease default CPU request/limit

- src/main/java/com/redhat/cloud/policies/app/EnvironmentInfo.java
- src/main/java/com/redhat/cloud/policies/app/JaxRsApplication.java
- src/main/java/com/redhat/cloud/policies/app/RouteRedirector.java
- src/main/java/com/redhat/cloud/policies/app/auth/IncomingRequestFilter.java
- src/main/java/com/redhat/cloud/policies/app/auth/RbacFilter.java
- src/main/java/com/redhat/cloud/policies/app/health/ProcSelfStatusExporter.java
- src/main/java/com/redhat/cloud/policies/app/health/StatusEndpoint.java
- src/main/java/com/redhat/cloud/policies/app/model/history/PoliciesHistoryRepository.java
- src/main/java/com/redhat/cloud/policies/app/rest/AdminService.java
- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/main/java/com/redhat/cloud/policies/app/rest/UserConfigService.java
Quarkus recently introduced a new `Log` API which delegates all its invocations to `org.jboss.logging.Logger`. Building the logger is no longer needed.
> Use the new Quarkus Log API

- src/main/resources/db/migration/V20__POL-650_history_org_id_index.sql
The policies history request is extremely slow from the frontend when the `orgId` is enabled because of a missing index.
This PR will fix that.
> POL-650 Add index-only scans to the policies_history table

- src/main/resources/db/migration/V20__POL-650_history_org_id_index.sql
The previous version of the migration script hasn't been executed yet on stage or prod. The migration failed on stage because it requires too much time and the pod gets killed by the health checks before the migration succeeds.
We will use index-only scans later, after the `tenant_id` has been removed from the DB. For now, a simpler index will be enough.
> POL-650 Make the policies_history index with org_id smaller

- .rhcicd/clowdapp.yaml
The next prod deployment will need more startup time because of an index creation. This should help preventing the pod from being killed because of probes failures.
> POL-650 Temporarily allow more probes failures

- .rhcicd/clowdapp.yaml
Reverts #471.
Prod DB has been migrated. This is no longer needed.
> Revert "POL-650 Temporarily allow more probes failures (#471)"

- src/main/resources/db/migration/V22__POL-650_policies_history_rule.sql
Initial rule: https://github.com/RedHatInsights/policies-ui-backend/blob/28054b0e41f6e37d6d006b89d8f505bdb041dd35/src/main/resources/db/migration/V18__POL-453-expose-last-triggered-to-policies.sql#L3-L6
> Use org_id in rule_policies_history_last_triggered

- .rhcicd/clowdapp.yaml
This patch adds `apiPath` to the public web service. This is in service to [RHCLOUD-20286  Policies new front end build process](https://issues.redhat.com/browse/RHCLOUD-20286)
You'll notice the commit looks like it replaces the entire clowdapp file. This is because the change is created by a tool that reads the YAML, edits it, and outputs it as part of the frontend migration process. I apologize if it is hard to read, but there is only one true edit here:
```
- name: service
minReplicas: ${{MIN_REPLICAS}}
webServices:
public:
enabled: true
```
becomes
```
- name: service
minReplicas: ${{MIN_REPLICAS}}
webServices:
public:
enabled: true
apiPath: policies
```
Let me know if you have any questions.
> Update clowdapp to have apiPath for webservice so front end can find it

- src/main/java/com/redhat/cloud/policies/app/model/history/PoliciesHistoryRepository.java
- src/test/java/com/redhat/cloud/policies/app/model/history/PoliciesHistoryRepositoryTest.java
Refactors `PoliciesHistoryRepository` to use native SQL to support Postgresql-specific queries (like JSON lookups).
RHINENG-1191
> refactor(repository): use native SQL for history

- src/main/java/com/redhat/cloud/policies/app/RbacServer.java
- src/main/java/com/redhat/cloud/policies/app/auth/RbacClient.java
- src/main/java/com/redhat/cloud/policies/app/auth/RbacFilter.java
- src/main/java/com/redhat/cloud/policies/app/auth/RbacRaw.java
- src/main/java/com/redhat/cloud/policies/app/auth/models/Access.java
- src/main/java/com/redhat/cloud/policies/app/auth/models/RbacRaw.java
- src/main/java/com/redhat/cloud/policies/app/auth/models/ResourceDefinition.java
- src/main/java/com/redhat/cloud/policies/app/auth/models/ResourceDefinitionFilter.java
- src/test/java/com/redhat/cloud/policies/app/RbacParsingTest.java
- src/test/resources/rbac_example.json
Adds parsing of `attributeFilter` from RBAC access responses.
Refactors tests to use Jackson, the same as the RestClient uses.
_Hint: review by commits_
RHINENG-1304
> feat(auth): RBAC attribute filters support

- .rhcicd/build_deploy.sh
This PR is pushing updates to the `build_deploy.sh` from the `security-compliance` branch that supports proper Image tagging when an image is built using the `security-compliance` branch.
> Pushing support for the Security-Compliance Image Build to `main/master`

- src/main/resources/META-INF/openapi.json
Updates OpenAPI's production server to point to console.redhat.com instead of the old cloud.redhat.com
> fix: Update production server

- pom.xml
- src/test/java/com/redhat/cloud/policies/app/NonApplicationRootPathTest.java
Upgrades to newest Quarkus 2: 2.16.12.
Refactors tests to support this upgrade, and cleans up direct dependency definition.
RHINENG-2697
> chore: update quarkus 2.16.12

- pom.xml
- src/main/java/com/redhat/cloud/policies/app/auth/RbacFilter.java
- src/main/java/com/redhat/cloud/policies/app/rest/PolicyCrudService.java
- src/main/resources/application.properties
- src/test/java/com/redhat/cloud/policies/app/TestLifecycleManager.java
OpenTracing has been deprecated in favor of OpenTelemetry in Quarkus.
Since, we are not actively using it, and have issues converting to OpenTelemetry (see #588), we're gonna drop it.
RHINENG-2951
> fix: drop unused and deprecated OpenTracing

- .rhcicd/clowdapp.yaml
Fixes
spec.jobTemplate.spec.template.spec.containers[0].restartPolicy: Forbidden: may not be set for non-init container
RHINENG-6805
> fix: restartPolicy in OS template

- .rhcicd/clowdapp.yaml
postgresql-rds "-1" images are being deprecated; moving to postgresql-rds:12 instead
> refactor(dev): update postgresql-rds image tag

- .github/workflows/checkupdate.yml
- src/main/docker/Dockerfile.jvm
This PR should replace of using UBI8 images with UBI9.
I was able to build new image with:
```
podman build . -f ./src/main/docker/Dockerfile.jvm -t test_build_policies_ui_backend --ulimit=nofile=4096
```
I confirmed that curl exists in the final image as I had to remove it from dockerfile due to installation conflict:
```
podman run --rm -it --entrypoint=sh localhost/test_build_policies_ui_backend:latest
sh-5.1$ 
sh-5.1$ curl --version
curl 7.76.1 (x86_64-redhat-linux-gnu) libcurl/7.76.1 OpenSSL/3.0.7 zlib/1.2.11 nghttp2/1.43.0
Release-Date: 2021-04-14
Protocols: file ftp ftps http https 
Features: alt-svc AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz NTLM SPNEGO SSL UnixSockets
```
RHINENG-12536
> Migrate container image/Dockerfile from UBI8 to UBI9

- .github/workflows/checkupdate.yml
Use jq to query for image digest to remove the need to rely on skopeo inspect output having json keys in particular order. RHINENG-13679
> fix(CI): use jq in checkimage

- src/main/resources/db/migration/V19__POL-650_add_org_id_columns.sql
- src/main/resources/db/migration/V6.sql
In order to have Policies running on different PG schemas, the migrations should not use fully qualified table names with the "public" schema.  Rather names of tables should stay schema-less, to leverage default schema set by search_path.
> fix: do not use public pg schema

- src/main/resources/application.properties
Runs repair on already applied migrations on start to match migrations that have been changed retroactively.
Ref: https://quarkus.io/version/3.15/guides/flyway
> fix(db): repair already applied migrations
